server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/small?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: rootroot

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: ksjdksdkfjdkssjdkfjsdk #JWT加解密使用的密钥
  expiration: 604800 #JWT的超期限时间(60*60*24*7)
  tokenHead: 'Bearer ' #JWT负载中拿到开头